services:
  siteup-redis:
    image: "redis"
    command: "redis-server /usr/local/etc/redis/redis.conf"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  siteup-frontend:
    build: ./siteup-frontend/
    ports:
      - "8000:80"
  siteup-backend:
    build: ./siteup-backend/
    env_file: ./siteup-backend/.env